sonar.projectKey=diego-silva1016_postech-fase-5-volunteer-service
sonar.organization=diego-silva1016
sonar.projectName=postech-fase-5-volunteer-service
sonar.sources=.
sonar.exclusions=**/__pycache__/**
sonar.python.version=3.11
