sonar.projectKey=diego-silva1016_postech-fase-5-donation-service
sonar.organization=diego-silva1016
sonar.projectName=postech-fase-5-donation-service
sonar.sources=.
sonar.exclusions=db/**
# ci: trigger build (donation-service)
# ci: retrigger
# ci: retest repo_token
# ci: fix push race + retest
