sonar.projectKey=diego-silva1016_postech-fase-5-ngo-service
sonar.organization=diego-silva1016
sonar.projectName=postech-fase-5-ngo-service
sonar.sources=.
sonar.exclusions=migrations/**,**/__pycache__/**
sonar.python.version=3.11
